### PR TITLE
Multimultitouch

### PR DESCRIPTION
**Pull request by velcrome**
Gives support and distinction for multiple multitouch screens, as provided by the windows event.

### CODE REVIEW

**Comment by velcrome** [comment]
i don't know why this PR is being bundled with the old (already closed) PR, even though it is in a different branch and all. please ignore the solution file, if it does show up on your end.

**Comment by azeno** [comment]
Well reset your local develop branch to our develop and only cherry pick the 603732c commit and create a new PR. That way the c31230d won't be inlcuded in the new PR.

**Comment by joreg** [comment]
ping @velcrome

**Comment by velcrome** [comment]
there is benefit in adding the wiimote in x64, and hence no need to cherry pick

go ahead with merge pls

**Pull request merged**
