### PR TITLE
Rope2d plugin and Rope (EX9) module

### PR DESCRIPTION
**Pull request by mhusinsky**
- a generic plugin for creating rope-like vertices and indices for a triangle strip in 2d
- a ex9 module using the plugin to create an ex9 layer

see here for the initial works
http://vvvv.org/forum/something-like-rope-in-dx11

(a dx11 module will be added in the respective gihub repo)

### CODE REVIEW

**Comment by joreg** [comment]
verygood so far. only please:
- put the heading of Rope (EX9) helppatch to its topleft (as all helppatches have it)
- remove the comparison part from the Rope (EX9) helppatch. just point out: see also Rope (DX9). rather make a second demo in the patch (with a second renderer) demoing different aspects of the module (like e.g. alpha, color)
- also while at it put a "see also Rope (EX9)" in the helppatch of Rope (DX9)
- tag the Rope (EX9) module: primitive, geometry
- inside the module Rope (EX9) you can disable VertexBuffer and Mesh 'Apply' if none of their inputs change to save some performance for static cases.

**Comment by mhusinsky** [comment]
thanks for your comments. please check the updated files.

**Comment by joreg** [comment]
great. one last thing: please put the comparison patch into \addonpack\girlpower and then dragdrop the file into the helppatch of Rope (EX9) while pressing ALT. this will give you an iobox with an "open" handle. now make the file link a relative one. 

like that the comparison patch is only actually loaded on demand and can also be found as a demo in the \girlpowers

**Comment by mhusinsky** [comment]
done.

**Pull request merged**
