### PR TITLE
adds [Syslog (String)] and [Logger (VVVV)]

### PR DESCRIPTION
**Pull request by sebllll**
a clean syslog PR

### CODE REVIEW

**Comment by joreg** [comment]
more cosmetics:
- help strings start capital
- tags should be all lower case
- no commas to separate tags
- no terms (like in your case "log") as tags that are already part of the nodename

**Comment by joreg** [comment]
is there a reason the syslog.csproj has only a Debug config and this is only x86
please have a look at other projects that typically have Debug, Release as AnyCPU

also it says the PR cannot be merged automatically animore. has to do with your change of the Addonpack.sln
please fix this on your side.

**Comment by joreg** [comment]
still cant automerge..

**Comment by sebllll** [comment]
now i pulled from upstream/develop and readded my .csproj

**Pull request merged**
