### PR TITLE
HTMLTexture loaded pin

### PR DESCRIPTION
**Pull request by woeishi**

### CODE REVIEW

**Comment by joreg** [comment]
interesting. can you add info about why this is needed as opposed to the already available IsLoading?

**Comment by woeishi** [comment]
talked it over with elias already. why this is needed...
if you add a slice, you don't know if IsLoading has triggered or not, or if it's even ever going to trigger. there have been a couple of patching hacks to get a clear state, but none could catch it properly....
a state is much clearer, and the IsLoading is only left for backwards compatibility

**Comment by joreg** [comment]
when opening the helppatch and pointing the texture to vvvv.org i see the "Is Loading" pin bang from time to time when a new image is being loaded for the "screenshots of the day". is that also reflected in the "Loaded" pin? if not i'd argue it is not only useful for backwards compatibility?! 

and the helppatch should probably be extended to show both next to each other and loose a few words as to what each is useful for?!

**Comment by woeishi** [comment]
this feature is not reflected. didn't even know it does that.

Loaded is relevant to get the actual texture size

On 01.12.2015 15:08, joreg wrote:

> when opening the helppatch and pointing the texture to vvvv.org i see
> the "Is Loading" pin bang from time to time when a new image is being
> loaded for the "screenshots of the day". is that also reflected in the
> "Loaded" pin? if not i'd argue it is not only useful for backwards
> compatibility?!
> 
> and the helppatch should probably be extended to show both next to each
> other and loose a few words as to what each is useful for?!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vvvv/vvvv-sdk/pull/269#issuecomment-160979258.

## 

Mag. (FH) Woeishi Lean
Generative- | Interactive Design

phon#: +43 650 963 47 44 | http://woei.refect.net/ | woei@refect.net | 
#woeishi

vitrine, Neulerchenfelder Str. 56/3, 1160 Vienna, Austria
General-Feurstein-Str. 25, 6020 Innsbruck, Austria
uid: ATU65290945

**Comment by joreg** [comment]
uk, anyway still missing an update to the helppatch that shows that there are now two pins that look similar but do something different and what they can be used for..

**Comment by woeishi** [comment]
here you go
helppatch improved

**Comment by joreg** [comment]
muchos gracias.

**Pull request merged**
