### PR TITLE
advanced versions for Button (3d Quad/Mesh Multitouch)...

### PR DESCRIPTION
**Pull request by mhusinsky**
... which provide additional info about the touched objects as well as the pointers touching the objects.

one thing that probably should be discussed is the naming of "cursor" vs. "pointer". i personally find "pointer" makes more sense for touch input because you could argue that a cursor (like a mouse cursor) is "always there", while a pointer can disappear.

any thoughts on this?

### CODE REVIEW

**Comment by azeno** [comment]
Hm why not add those new output pins to the existing modules? Pin re-naming without breaking existing patches can be done with the diffff.xml: https://github.com/vvvv/vvvv-sdk/blob/develop/vvvv45/addonpack/diffff.xml
And yes I'd also prefer Pointer over Cursor.

**Comment by mhusinsky** [comment]
i'll add them to the existing modules.
i'm having problems figuring out the difff.xml though.
using the syntax as described in the comment of difff.xml has no effect (old patches are still broken).

`<NODE old=":MODULES:\3d\Button (3d Mesh Multitouch).v4p">
        <PIN old="Cursor Transform" new="Pointer Transform" />
    </NODE>`

where could i be wrong?

**Comment by azeno** [comment]
Did you increase the version of the addonpack (https://github.com/vvvv/vvvv-sdk/blob/develop/vvvv45/addonpack/version.info)? For example from 33.8.0 to 33.8.1? And in the diffff you add those changes for the new 33.8.1 version.

**Comment by joreg** [comment]
ping

**Comment by mhusinsky** [comment]
i finally got the bugger that prevented the difff.xml from being applied correctly. while the comments at the beginning of the file suggest to use this notation for module names:

```
:MODULE:\ModuleName (Version).v4p
```

it was actually not nescessary to do the pin renaming. took me a while to figure this out...

**Pull request merged**
