### PR TITLE
adds some new options for MathRound

### PR DESCRIPTION
**Pull request by sebllll**
still not sure about this diffff...

### CODE REVIEW

**Comment by joreg** [comment]
diff is fine only the actual old node needs to have version "Legacy" added.

**Comment by joreg** [comment]
Addonpack.sln has >600 additions..that seems too much!

**Comment by sebllll** [comment]
updated the PluginInfo, but have no idea ho to change the diff... hint?

that's how it looks atm:

```
<PATCH version="45alpha33.4">  
    <NODE old="MathRound (Value)" new="MathRound (Value Legacy)"></NODE>
</PATCH>
```

**Comment by sebllll** [comment]
the 600+ change lines in the .sln happen as soon as i just open it (with VS2013)

**Comment by joreg** [comment]
as i said: the difff is fine. only the old node needs to get a version. the sln changes... are they more than whitespace?

**Comment by joreg** [comment]
@sebllll now this can't be merged automatically. please check.

**Comment by sebllll** [comment]
now?

**Comment by joreg** [comment]
still: whats the 600lines of changes in the .sln? it says 624 additions. i can't see on here what those are...

**Comment by sebllll** [comment]
same as before, those changes appear as soon as i open the sln... in case it doesn't merge correctly, can you just insert the .csproj in your 'clean' .sln?

**Comment by joreg** [comment]
"those changes appear as soon as i open the sln..."
ok, but what kind of are they?

**Comment by sebllll** [comment]
image
maybe that's nuget-related, made by nuget-restore... which you mustn't do?

**Comment by azeno** [comment]
The Nuget build configuration is used by our build server to create the nuget packages. For now this is only done for our core projects. The configuration is defined in common/src/Default.Project.settings which every project in our solution should include. Your IDE simply completes the solution file. No idea why mine didn't. I'll double check and report back.

**Comment by azeno** [comment]
Yeah well my VS2013 doesn't add those lines. In any case @joreg I think it's safe to include them.

**Comment by sebllll** [comment]
this is fine now?

**Comment by joreg** [comment]
looking good now. thanks.

**Pull request merged**
