### PR TITLE
fixed Octonion operations

### PR DESCRIPTION
**Pull request by fibo**
I changed the & operator with the Vector4D 's "*" overloaded operator

### CODE REVIEW

**Comment by joreg** [comment]
hei fibo,

thanks for that fix. but. for some reason git thinks Octonion.cs is a binary file and does not show us the diff. you see? opening the file in a text-editor shows that you saved it as utf16. please fix that or let us know the reason for doing so.

**Comment by fibo** [comment]
I really don't know why, maybe could be related with the facet I used Visual Studio 2012 on Windows 8 ... whatever, I'll redo the modifications via browser :)

**Comment by fibo** [comment]
mmh, it seems it is already utf16 in the upstream repo, see https://github.com/vvvv/vvvv-sdk/edit/develop/vvvv45/addonpack/src/nodes/plugins/8d/Octonion/Octonion.cs

**Comment by joreg** [comment]
ya, seems its been uft16 before. should still be easy to fix. with  e.g. notepad++ you can save the file to plain ascii...

**Comment by fibo** [comment]
Should be ok now, I did another push https://github.com/vvvv/vvvv-sdk/pull/113
if it is ok I will edit the help patch and create a Fano plane

**Pull request closed without merging**
