### PR TITLE
Fixed the Encoding 125_0_ did not work on current tests, 1252 does work

### PR DESCRIPTION
**Pull request by jnslxndr**
Silly encoding. Will be gone with RAW. Rohkost in the works...

### CODE REVIEW

**Comment by joreg** [comment]
but in the last PR you specifically mentioned that 1252 did not work?! 
see https://github.com/vvvv/vvvv-sdk/pull/93

**Comment by jnslxndr** [comment]
yes, i know. grmpff.. either me was not testing thoroughly on the last PR or something "changed somehow". i'll checkout and recompile the snapshot from the last PR to see what happened.

another question, which could be useful likely drop this PR: when is the next release cacle planned? i am pretty confident with the stream things.

**Comment by jnslxndr** [comment]
sh...ame on my bloody pre-christmas-stress-syndroma... i can't recall, what had occured to me, that it did not work. re-checkout showed, 1250 works as input, but not as output decoding. i take it. sorryyy.

still the question on plans. as far as i can oversee the next week(s) the transition to the raw datatype can be done. so i think about releasing the module as a drop in replacement on the contributions page. sinnvoll?

**Comment by joreg** [comment]
there shall be a b29.1 in time for node. would of course be great to have your raw-update in alphas asap to get it a little tested before it is being used with b29.1 at node

**Comment by jnslxndr** [comment]
thx for sharing the planning!
after i surrendered to the strangeness of windows view on things, i think i finally wrapped my head arround the stream things and have a first working version on Raw: https://github.com/muthesius/vvvv-sdk/commit/040b7526d88e6ea5e73417b9cab2d8d0cd65793a

if of any help, this is the branch https://github.com/muthesius/vvvv-sdk/tree/virmata-rohkost

i hope no one minds the Rakefile...

**Comment by joreg** [comment]
ok, so this should get some testing from people. 2 options: 
- post it in the alpha forum with instructions on how people can test it. 
- send us a pullrequest and we include it in the alpha (probably more convenient for people?)

**Comment by jnslxndr** [comment]
sers, herr ioreg.
yes, i think so too. but not to make too may changes within a single PR, i will review some minor issues with it tomorrow, then post on both locations.

i think we can close this one here unmerged.

**Pull request closed without merging**
