### PR TITLE
Added ShellExecute (Windows Advanced)

### PR DESCRIPTION
**Pull request by smakhtin**
Hope now it will be ok.

### CODE REVIEW

**Comment by joreg** [comment]
hm..Addonpack.sln looks strange. github won't show its diff and when viewing it manually i see ~500 strange lines inserted. please just revert changes to Addonpack.sln and i'll add the csproj over here.

**Comment by smakhtin** [comment]
Hmm, i just added a project by Visual Studio. How you adding it?

**Comment by joreg** [comment]
will also try with visualstudio...will have to observe the diff..

**Comment by smakhtin** [comment]
Ok, i did a revert of Addonpack.sln. What else?

**Comment by joreg** [comment]
that will do..

**Pull request merged**
