### PR TITLE
Wake On LAN node

### PR DESCRIPTION
**Pull request by sebllll**
just a simple WOL node. works fine here...

i'm unsure if this pullrequest is fine.

### CODE REVIEW

**Comment by sebllll** [comment]
i only wanted to pullrequest this commit: c7e13d633d2e104f74cc3f84880c32a5bc47472d

i have no idea why there's 16 commits in there

---

The following changes since commit c7e13d633d2e104f74cc3f84880c32a5bc47472d:

  added WOL (Network); (2013-05-23 15:51:01 +0200)

are available in the git repository at:

  https://github.com/vvvv/vvvv-sdk 

for you to fetch changes up to c7e13d633d2e104f74cc3f84880c32a5bc47472d:

  added WOL (Network); (2013-05-23 15:51:01 +0200)

---

**Comment by azeno** [comment]
develop: A -> B -> C -> D 
yours: A -> e7e7882 -> B' -> C' -> D' -> c7e13d6
where B' is merge of B, C' merge of C etc.
these are all merge commits because your branch diverged from ours with commit e7e7882 (Revert "new code for ...")
so what's this e7e7882? is it needed? was it a mistake?

**Comment by sebllll** [comment]
i never intentionally touched the code mentioned in e7e7882 . so, it's a mistake... i wasn't able to pullrequest only the commit c7e13d6

**Comment by azeno** [comment]
you could make a backup branch of your current state, like this
git checkout -b develop-backup
go back to develop
git checkout develop
after that fetch latest changes
git fetch upstream
and reset your local develop branch to upstream (make sure you don't have any uncommitted changes)
git reset --hard upstream/develop
now cherry pick the c7e13d6
git cherry-pick c7e13d6
force push your changes to your github repo and make a pull request.

**Comment by woeishi** [comment]
git checkout -b develop-backup
git checkout develop
git pull --rebase upstream/develop
git cherry-pick the ones from develop-backup

**Comment by sebllll** [comment]
ok, thank you very much guys. i'll do exactly what you suggested when i'm back on my dev-machine

**Comment by sebllll** [comment]
does it work now?

**Comment by azeno** [comment]
looks much better now but still a little weird: 
1) two commits, where the first one doesn't contain anything
2) pls remove WOL/PluginInfo.cs

**Comment by sebllll** [comment]
i had to commit a message-only commit to conclude the cherry-pick. i wasn't able to pull from my fork without that. weird anyway.

but once again, i removed WOL/PluginInfo.cs

**Comment by azeno** [comment]
hmm seems like you accidentally merged the troublesome commits back in?

**Comment by sebllll** [comment]
ok, another try. i'm pretty sure everything's allright now

**Comment by azeno** [comment]
ok looks good now. thank you.

**Pull request merged**
