### PR TITLE
improvement on indices > Input.Slicecount

### PR DESCRIPTION
**Pull request by woeishi**

### CODE REVIEW

**Comment by tebjan** [comment]
there was no need for that, we tested the bahavoir with indices out of the range, the RemoveAt() method already does the modulo

**Comment by tebjan** [comment]
i think its more important to check for IsChanged on the inputs because of you don't want to do a sort each frame...

**Comment by woeishi** [comment]
RemoveAt() does modulo, but Distinct() is applied beforehand, so doubled indices (which are only the same index after a modulo operation) are not taken account of.
try input [0..2] and remove index [0,3].
IsChanged is a good idea indeed

**Comment by tebjan** [comment]
ah, i see!

**Pull request merged**
