### PR TITLE
Quick fixes for upcoming beta release

### PR DESCRIPTION
**Pull request by velcrome**
second attempt, lets see if this shows up easier

### CODE REVIEW

**Comment by joreg** [comment]
hei velcrome, thanks for this but may i ask you to have a look at the Matrix2x2.cs file again where you seem to have unnecessarily changed whitespaces. i know this is kind of a mess to deal with, so here some info:

tabs are being delt with differently in different IDEs. some make a tab an actual tab, others make them a specified number of spaces. and then when doing automatic codeformatting those IDEs replace all with their setting. so this is the most likely way this was caused. 

sharpdevelop defaults to tabs (and i cannot talk about the defaults of other IDEs) and we at some point agreed to change the setting to replacing tabs by 4 spaces. so thats what we work with now and thats what we want. looking at an old version of Matrix2x2.cs i see it has spaces, not tabs so please check that again.

**Comment by velcrome** [comment]
hey joreg, thanks for the reply

i will look at this tomorrow, still too busy to get my working environment back.
crashed my harddrive last week but luckily i pushed before the hd's mbr went into outer space

**Comment by velcrome** [comment]
today i found the time to look at it again. you were right about the kind of mess, but unfortunately not about the whitespaces.
tbh i do not understand why github shows all these unnecessary changes, both the line endings and the tab encoding match up in Matrix2x2.cs to previous versions of the file. local diff reports very differently, please check yourself.

**Comment by joreg** [comment]
hah, i just found via https://github.com/blog/967-github-secrets that you can view a diff with whitespace changes ignored by adding ?w=1 to the url. so that helps. anyway it seems to me Matrix2x2.cs had unix lineendings and now its windows style. so that would be fine.

but! please put unrelated stuff in separate pull-requests. so here we have:
- tostring methods added
- spacemouse tuned
- rfid64 added 
- map advanced

how to make separate pullrequests? put unrelated stuff in separate branches on your end and then pull those against our develop. like this we get a much better overview of whats going on and can much quicker pull stuff in.

**Comment by joreg** [comment]
closed for being split up in several PRs now.

**Pull request closed without merging**
