### PR TITLE
(Touch)Gestures

### PR DESCRIPTION
**Pull request by woeishi**
via wm_gesture

### CODE REVIEW

**Comment by azeno** [comment]
Regarding VL: I guess I'll have to add imports to VVVV.Utils.dll.vlimport for the GestureNotification class same as we did for Mouse and Keyboard? Will do as soon as a new VVVV.Utils NuGet is out.

**Comment by woeishi** [comment]
it's modelled equivalent to the touch implementation we did. so 
importing notification classes and the bools should do

On 04.01.2016 17:30, Elias Holzer wrote:

> Regarding VL: I guess I'll have to add imports to
> VVVV.Utils.dll.vlimport for the GestureNotification class same as we did
> for Mouse and Keyboard? Will do as soon as a new VVVV.Utils NuGet is out.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vvvv/vvvv-sdk/pull/271#issuecomment-168724817.

## 

Mag. (FH) Woeishi Lean
Generative- | Interactive Design

phon#: +43 650 963 47 44 | http://woei.refect.net/ | woei@refect.net | 
#woeishi

vitrine, Neulerchenfelder Str. 56/3, 1160 Vienna, Austria
General-Feurstein-Str. 25, 6020 Innsbruck, Austria
uid: ATU65290945

**Comment by azeno** [comment]
Just wanted to do the import, when I noticed that certain important information like distance/rotation/pan is not available on the gesture notifications itself, instead that information is hidden in the implementation of the nodes. Wouldn't it be nicer to have these things as properties in the notification classes? 

```
public double Distance => (double)(this.Arguments & Const.ULL_ARGUMENTS_BIT_MASK);
```

Normalization code such as distance / (clientArea.Height \* 2) could stay in the VVVV/VL specific nodes.

**Comment by woeishi** [comment]
jap, probably true. haven't thought this all through, wanted to give it 
a try, doing some sketches in vl first, before finalizing those classes 
(wave @joreg). since i guess it might look a little bit different to the 
implementation in vvvv due to the possibility of having states for the 
arguments.
the line you pointed out makes sense though, since it is used for all 
gestures nearly equally. some need it cast to double some to int. wasn't 
sure yet how to handle that cleanly in vl.

On 05.01.2016 15:10, Elias Holzer wrote:

> Just wanted to do the import, when I noticed that certain important
> information like distance/rotation/pan is not available on the gesture
> notifications itself, instead that information is hidden in the
> implementation of the nodes. Wouldn't it be nicer to have these things
> as properties in the notification classes?
> 
> |public double Distance => (double)(this.Arguments &
> Const.ULL_ARGUMENTS_BIT_MASK); |
> 
> Normalization code such as distance / (clientArea.Height \* 2) could stay
> in the VVVV/VL specific nodes.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vvvv/vvvv-sdk/pull/271#issuecomment-169010639.

## 

Mag. (FH) Woeishi Lean
Generative- | Interactive Design

phon#: +43 650 963 47 44 | http://woei.refect.net/ | woei@refect.net | 
#woeishi

vitrine, Neulerchenfelder Str. 56/3, 1160 Vienna, Austria
General-Feurstein-Str. 25, 6020 Innsbruck, Austria
uid: ATU65290945

**Pull request merged**
