### PR TITLE
a few bullet vehicle options added including skidinfo for wheel trails

### PR DESCRIPTION
**Pull request by wirmachenbunt**

### CODE REVIEW

**Comment by joreg** [comment]
@mrvux can you please comment on that?

**Comment by mrvux** [comment]
Missed that in email notifications, basically it's all the extra params which are pretty needed for better simulation :)

**Comment by joreg** [comment]
so you say it is good to merge?

**Comment by mrvux** [comment]
looks fine by me

**Comment by wirmachenbunt** [comment]
cheers for the approval. there will be another pull request containing vehicle speed output and a help file. just realized these are missing. sorry...

**Comment by joreg** [comment]
no problem just add to this PR

**Comment by tebjan** [comment]
Please also check that the pin names follow our specs. Start with capital and spaces between words.

**Comment by joreg** [comment]
@wirmachenbunt what's the state of this?

**Comment by joreg** [comment]
danks.

**Pull request merged**
