### PR TITLE
PolygonEditor

### PR DESCRIPTION
**Pull request by DominikKoller**
Reopening this: 
https://github.com/vvvv/vvvv-sdk/pull/199

-Cursor (DX9) and Drag (Value) have been removed from PolygonEditor, and seperately added to the addonpack.

-The helppatch is fixed

Renamed subpatches as discussed. They are now called 'Feature (PolygonEditor)', and SplitData/JoinData is now called PolygonEditor (Split/Join).

Also changed the logic of OnlyOneTrue, to be one file instead of two different ones for Vertices and Polygons, and also to be possibly usable outside of PolygonEditor.

Still have to do the renaming of all Pins, so the word Shape is gone everywhere (we are dealing with Polygons, which is more specific than shapes; also, most of the time it's obvious that we are dealing with properties of Polygons (like Polygon Vertex Count etc.), so it can and should be left out altogether to avoid doublestatements).

### CODE REVIEW

**Comment by DominikKoller** [comment]
All Pins are now renamed, as discussed.

**Comment by joreg** [comment]
herewego:
- CircumRectangle is missing the taged-connection. 
- i see a S/R used. they are global so we can't use them in modules..
- PolygonEditor (join/split)'s in/out should just be called "Input" and "Output"
- Split/Join are no categories. should be PolygonEditor (2d Split/Join)
- in PolygonEditor (2d Split) try to avoid DeleteSlice alltogether. try CAR and GetSpread...
- MoveVertexKeyboard -> MoveVertex (so it better corresponds to DragVertex)
- place the main PolygonEditor (2d) module directly into \2d and all the submodules into \2d\PolygonEditor (ie, get rid of the \sub)
- only use one MouseStates (Split) in PolygonEditor (2d) 
- replace DoubleClick with (stilltocome) native node
- use only one Mouse (Devices Window) node in helppatch
- discuss: generalize and find a better name for OnlyOneTrue
- discuss: could PolygonEditor (2d) just have an "Output" and i have to use a PolygonEditor (2D Split) to access its data? now they seem to have different outputs..

**Comment by DominikKoller** [comment]
- Renamed (2d Join/Split), In/Output Pins; removed S/R
  Do you think it is clear enough that MoveVertex only covers moving a vertex with the Keyboard? When it's called MoveVertex, wouldn't you expect something more general? With DragVertex it's pretty clear, when the user drags something that's clearly with the mouse.
- are you sure we should use only one MouseStates (Split)? That would cause the main Patch to be much messier, lots of Inputs going to the Subpatches like MouseXY, Left Button, Right Button, instead of one Mouse Input and then a Split where it needs to be split.
- I think having only one output and having to use Split to get it's data is a great idea! I could make a Node that takes that output and gives you a ex9 Layer, visualizing the data much like the helppatch does now. The problem with that is that Outputs like Mouseover or Cursor Type are not in the feedback loop, and therefore not included in Join/Split. We'd have to have one Output + Vertex Mouseover, Mouseover and Cursor Type Outputs. 

Why avoid DeleteSlice?

**Comment by joreg** [comment]
- MoveVertex has a Keyboard input..so that should be telling..could also get a "keyboard" tag..
- re: mousstates: i mean only one per patch
- re: DeleteSlice: just so..i'd guess the others are faster

**Comment by DominikKoller** [comment]
Alright, should be all done now! (except for doubleClick)

**Comment by joreg** [comment]
getting there...
- all subpatches should be hidden
- none of the patches/renderers should be set to "AlwaysOnTop" (Ctrl+T)
- Mouse connection to ..View missing in helppatch
- Cons - Initial Vertices -> make this a comment rather than a node-label
- in the helppatch make all descriptions of the inputs comments, like: < Insert
- i can now only select shapes but not individual vertices?!
- still: only use one MouseStates (Split) in PolygonEditor (2d) 
- not sure about IsActive. should be called "Enabled" but maybe even use "Evaluate" instead?

**Comment by DominikKoller** [comment]
Oh, sorry, I was messing with things after I wrote this message. Now the selection of individual vertices is working again.

IsActive: maybe call it Enable Interaction? Because that's essentially what it does.

**Comment by DominikKoller** [comment]
Take a look at the solution I tried for the Cursor Enum. I made a new Node called CreateEnumCursorType (Cursor), put it in a subfolder in /EX9 where the Cursor node is called /EX9/Cursor, and used that inside Cursor and Initialize in PolygonEditor to create the Enum.  

PolygonEditor is still red, which is weird. It becomes grey as soon as you do anything with Initialize, e.g. open it or retrieve it's values.

**Comment by DominikKoller** [comment]
Alright, removed IsActive. Evaluate does its job much better anyway. 

Also made bugfixes (tagged polygons and vertices are handled better internally now, tagged vertices behave properly also when polygons are tagged).

**Comment by DominikKoller** [comment]
Alright, should be it for now! 

Stuff that still has to come:
Rotating

maybe adding Points to Polygons/ deleting Points to Polygons. However, this wouldn't be useful in BadMapper (we intended this module to be used inside BadMapper).

**Comment by joreg** [comment]
very good. please add to the changelog: http://vvvv.org/documentation/addons-change-log-45beta32.3-01

**Pull request merged**
