### PR TITLE
stupid error in syslog (raw) and a cosmetic in Logger (vvvv)

### PR DESCRIPTION
**Pull request by sebllll**

### CODE REVIEW

**Comment by joreg** [comment]
- Logger (VVVV) help still has SysLog written in its helppatch
- syslog join/split seem to share a helppatch. if so please make only one and both link to the same. see how e.g. the zip nodes do it.

**Comment by joreg** [comment]
hm..and as you point out in the credits you used code of amazing-andrew.  he doesn't seem to have a license on his code or did you find some? it seems you took his code but modified it into your own .cs files? but those no longer seem to have a reference to the original? can you clarify on that?

**Comment by sebllll** [comment]
ai, that's right. i didn't find a license on this, but contacted andrew and he's fine with this plugin. see here https://github.com/amazing-andrew/Syslog/issues/1

and i didn't see the structured-data-parser fail during my testing...

**Comment by joreg** [comment]
ouright then its in now. thanks.

**Pull request merged**
