### PR TITLE
Fixed null pointer exception on KinectRuntimeNode.cs and added KinectDept...

### PR DESCRIPTION
**Pull request by ravazquez**
...hPointCloudNode

The KinectDepthPointCloudNode receives a KinectRuntime input, and
outputs XYZ coordinates for the data read in from the depth stream.  A
resolution pin allows for all pixels in the stream to be considered, on
a division of the full amount of pixels by the factor specified in the
resolution pin.

The null pointer exception ocured when attempting to close vvvv while a Kinect (Microsoft) node was inside the patch.

### CODE REVIEW

**Comment by joreg** [comment]
hei ravazquez, thanks fo rhtis. please see my inline comments. and as a general note: please don'T commit fixes and features in the same pullrequest. while i'd immediately accept the fix, the feature needs some more discussion and since they have nothing to do with each other the feature just blocks the fix..

**Comment by ravazquez** [comment]
Thanks for the quick and various comments joreg.  I greatly respect your work.   Sorry if I messed up on the tags and comments, first time trying to contribute so I am still learning the ins and outs of your workflow here : ) .  

So, here are my questions/comments for now, hope you can help:
1. Are there guidelines somewhere as to how to submit a proper pull request, how to go about comments and such?
2. Can this pull request be undone so that I can add the fix and the new node on separate requests?
3. I can easily change the pin names to the names you suggested, which are indeed more intuitive.
4. As for the XYZ coordinates, I guess they can be sent out as XYZ vector instead of separate output pins.  

However, just so you get the idea of what is going on, X for now is the pixel id from 0 to 320 and Y from 0 to 240 (320x240 resolution on the depth stream, which for now is hardcoded as it was on the KinectRuntime Node but needs to be variable in the future) while Z is a value ranging from 0 to 4000, where 0 is the value for points where depth data is unreliable (too close, shadowed outline, etc) and 4000 is the maximum range at which the kinect depth stream operates.  The Z number is a measurement in mm.

This means that converting Z to meters should be fairly simple, however, doing the same for X and Y is not as straightforward to me as of yet.  Specially since objects closer to the sensor will cover a larger X,Y range while objects further away will cover smaller X,Y ranges.  Any ideas?

Thanks again, hope I will get in line with your workflow soon to increase the amount of contributions to the community : )

Gotta lovvvve vvvv!

**Comment by joreg** [comment]
ad 1) i updated the section "contributing.." in http://vvvv.org/documentation/vvvv-sdk and added some infos regarding pullrequests

ad 2) pull-requests can only be closed. so as i described in the updated document above you can simply start 2 new pullrequests by committing the changes to separate branches on your end and then PRing from those

ad 4) ja there is a conversion routine from projective coordinates (which you're using) to the more intuitive real-world coordinates. please check the ProjectiveToRealworld (3d Kinect) module. to my understanding this is what you'd need. and then i'd apply this conversion already inside the node..does that make sense?

**Comment by joreg** [comment]
closing this. please re-pullrequest us the 2nd part of this as you did with the first part here:
accepted https://github.com/vvvv/vvvv-sdk/pull/164

**Pull request closed without merging**
