### PR TITLE
Line (EX9) is splitted in two modules.

### PR DESCRIPTION
**Pull request by antongit**
Plus:
- legacy 
- Line_Test just for now

### CODE REVIEW

**Comment by joreg** [comment]
ok, this is missing 
- a diff entry for the legacy module:
- two extra helppatches for the two new nodes

transform each bin works differently now on the fromto module. in your test-patch change the second rotate-slice to see. 

the "transform each bin" pin and also the bin size still makes sense there. in both cases if this pin is 0 all of the lines get duplicated as many times as there are slices on the transform. if this pin is 1 the transforms apply bin-wise to the lines.

**Comment by joreg** [comment]
- remove (now quite legacy) "Attention" from helppatch
- "Closed" not featured in (top of) helppatch 
- to "see also: Line (fromto)" add "which works exactly the same except it takes 2 points (from and to) as inputs instead of a single spread" and move it right below the title of the patch (where the "attention" was) and add similar for the other versions helppatch
- in case binsize = 2 and closed = 1 nothing should happen (now draws line twice)

**Comment by antongit** [comment]
Hi Joreg,

thank you. Everything is done.

**Comment by joreg** [comment]
can we get rid of Lines_Test?

**Pull request merged**
