### PR TITLE
spacemouse rewrite for plugininterface 2

### PR DESCRIPTION
**Pull request by velcrome**
spacemouse tested for x64
phidgetrfid tested for x64

### CODE REVIEW

**Comment by joreg** [comment]
also the helppatch has a connection missing to the Buttons iobox

**Comment by velcrome** [comment]
thanks for the feedback, will take care of it when time allows

**Comment by joreg** [comment]
@velcrome shall we close this one for now? can't be merged anymore anyway..

**Comment by velcrome** [comment]
The fact remains. Both plugins are good for x64. Maybe you just add them to the solution any way you like.

**Pull request merged**
