### PR TITLE
Added OSC support for blob, color, timetag and char.

### PR DESCRIPTION
**Pull request by velcrome**
Implemented Blob, TimeTag, and Color support for OSC utils

Added an ExtendedVVVVMode to add useful type additions to OSC for internal communication (Vector2D, Vector3D, Vector4D and Matrix4x4)

### CODE REVIEW

**Comment by tebjan** [comment]
ok, sounds fine to us, as the directx matrices are float anyways.

**Comment by velcrome** [comment]
I removed the (long timestamp) constructur, because long does not seem to a good way to use a timestamp. In vvvv a fixed point double is used, in c# you use DateTime, etc. 

Ofc I cannot be sure that it might break some code, but I reckon the chances for it quite slim, because using this constructor does not give any additional functionality at all as compared to the default constructor. The timestamp was never really implemented, I think this constructor was really just a mock-up for functionality to come.

**Comment by velcrome** [comment]
"v" is for small vector - 2D, "V" for bigger vector - 3D, "Q" for Quaternion

I tried to fit the characters into the scheme of the other string types, as of http://opensoundcontrol.org/spec-1_0 and it seemed to make sense to me, especially because these characters are weird enough to not show up in official osc sometime in the future. 

But I guess it is a matter of taste as of now anyway, if you think it makes a difference feel free to edit

**Comment by tebjan** [comment]
they are strange indeed. but 'm' is used for midi messages if you use M that could be confusing. but i have no better suggestion. if we would use 2 and 3 then 16 would be nice, but that's out of choice of course. i saw that you can send arrays, how about [dd], [ddd] and [ffffffffffffffff]? but that would blow up the data... so i am fine with the original commit.

**Comment by joreg** [comment]
ic about the constructor. but couldn't it still be left in place and then now just work as it could take the long and make it into a DateTime? then existing could would not break but suddenly finally work.

**Comment by velcrome** [comment]
added constructor to follow joregs concerns.

and talking about the midi note option- if you introduce something like that for the sound libs, i'd be happy to add it as well as soon as the c# declaration is set.

**Pull request merged**
