### PR TITLE
Combinatorics Nodes

### PR DESCRIPTION
**Pull request by bj-rn**
CombinatoricsNodes wrap combinatorics implementations of Adrian Akison, taken from his CodeProject article

http://www.codeproject.com/Articles/26050/Permutations-Combinations-and-Variations-using-C-G

Contains:
Combinations (Color Combinatorics)
Combinations (Spreads Combinatorics)
Combinations (String Combinatorics)

Permutations (Spreads Combinatorics)
Permutations (String Combinatorics)

Variations (Color Combinatorics)
Variations (Spreads Combinatorics)
Variations (String Combinatorics)

### CODE REVIEW

**Comment by joreg** [comment]
is any of those doubling functionality of the Pairwise nodes?

**Comment by bj-rn** [comment]
To be honest I wasn't even aware of the Pairwise nodes... 
From the description on vvvv.org I'd say they are similar to the Combinations Nodes.

"Returns all combinations of successive slices. From an input ABCD returns AB, BC, CD "

Have to check out the pairwise stuff or you could have a look at Combinatorics, I posted a compiled version here:

http://vvvv.org/contribution/combinatorics-nodes

**Comment by bj-rn** [comment]
They are different, I missed the "successive". The Combinations nodes will return all possible combinations.

 ABCD returns AB, AC, AD, BC, BD, CD. 
Also you can of course change the subset element count to something different than 2.

**Comment by joreg** [comment]
regarding the license:
Place a file called

 license-MYPLUG.txt 

directly in the directory of your plugin. From there it will be automatically collected and put in the common \addonpack\licenses directory after the build.

**Pull request merged**
