### PR TITLE
adding more generic StepperController node + some bugfixes

### PR DESCRIPTION
**Pull request by woeishi**
- Unipolar4Motors node is now also compatible to Bipolar 1-Motor phidget device
- GetSpread bugfix and speedup

### CODE REVIEW

**Comment by joreg** [comment]
hm...last 2 commits seem to be not related to the description given in the pullrequest..

**Comment by woeishi** [comment]
ah, jop. wanted to open another pull req. for the bugfixes.
seems like github appends further commits automatically.
can change the description

**Comment by joreg** [comment]
would prefer separate requests for unrelated stuff. easier to check/handle

**Comment by woeishi** [comment]
ok, let's see, guess i have to open another branch for that?

**Pull request closed without merging**
