### PR TITLE
Binary operators

### PR DESCRIPTION
**Pull request by jnslxndr**
First attempt to implement binary operators as plugin nodes.
not too sure, if this is right approach, but spread extensions seem to be more detailed work.

not sure where to put the help patch - or even if one is needed for these expert nodes!?

### CODE REVIEW

**Comment by azeno** [comment]
help patches go to vvvv45/lib/nodes/plugins - but i think the help text in the node should be enough to explain its functionality

**Comment by jnslxndr** [comment]
i thought so too. just seen the faulty naming. shame on me...

**Comment by joreg** [comment]
the nodenames <<, >>, &, |, ~ and ^ will likely cause troubles.. you'll have to add some entities to the \lib\vvv.dtd for those. and then use the stringnames in the code here. vvvv then substitutes them for display. 

concerning &, |: would it make sense to also write them as AND, OR as they are now in vvvv or should we rename vvvvs AND, OR nodes to &&, || respectively?

also not sure about setting a version of "Bitwise" for all those nodes.. probably a tag "bit" would do?

**Comment by jnslxndr** [comment]
> concerning &, |: would it make sense to also write them as AND, OR as they are now in vvvv or should we rename vvvvs AND, OR nodes to &&, || respectively?

hehe. if you like!? but i think this might be very confusing. i stuck to the _nerdy_ naming because these are nerdy tools. but it sounds quite complicated to have the names pop up in the UI. i give it a try as soon as possible.
well, concerning version or tag, imho these nodes are versions, if the naming will be compliant to the existing `AND`, etc. otherwise, yes, maybe the tag is more appropriate. have to think about it.

**Comment by joreg** [comment]
> but it sounds quite complicated to have the names pop up in the UI.

forget what i said about it. it is wrong. we'll have to define the symbols internally before you'll be able to use them..will come back to this..

**Comment by jnslxndr** [comment]
before you do any internal adjustments, i'll better switch to a wordish naming!
actually they worked fine in the patches when i used them...

**Comment by tebjan** [comment]
yes, please change the node names to words like ShiftLeft/ShiftRight/AND/OR/... basically like the boolean category in the node browser. And don't forget to add some tags which might help to find them.

**Comment by tebjan** [comment]
bump..:)

**Comment by tebjan** [comment]
hello jens, are you still working on this?

**Comment by joreg** [comment]
closing this because of inactivity

**Pull request closed without merging**
