### PR TITLE
Vlc

### PR DESCRIPTION
**Pull request by mrft**
Hello, I have finally created a version that I think could be put into the addonpack. I hope you will find it is stable enough, and everything about licensing is ok.
If so, maybe this could still go into the beta28 addonpack. Of course, apparently due to some SlimDX limitation, I am not able to inform vvvv if Vlc is outputting dx9ex shared textures (so that part is not entirely finished), but I don't think that should hold me back from (finally) adding it to the addonpack.

First pull request ever, and still very much learning how to handle git, so if you have any problems, or missing files, please let me know...

### CODE REVIEW

**Comment by joreg** [comment]
hei ft,

great. we'll check this out soon an integrate it in the next alpha build as soon as we have beta28 out.

**Comment by gregsn** [comment]
hi again!

well i was too fast with accepting your pull request...
you changed the myplugins project & myplugins solution. but those are meant for all users and are somehow meant to be empty templates where it is easy to start from... so think about making copies of myplugins solution and myplugins project, which then serve you as environment you always can change as you like. it then also doesn't hurt when it is commit to the public. this then only means that others can open your "view" onto the addonpack... 

then there were some files changed that shouldn't be changed. in fact since this commit only adds functionality no file should be changed, only files added.

finally i saw your comments about the GPL license issues. so if in fact only the bindings could be the problem then did you check the different options? http://wiki.videolan.org/C_Sharp this one http://forum.videolan.org/viewtopic.php?f=32&t=52021 for example is LGPL which shouldn't make any difficulties as long you don't change those binding files without sharing again...

**Comment by gregsn** [comment]
the problematic part is this:

http://www.gnu.org/licenses/gpl-faq.html#GPLPluginsInNF

which means as long parts of our code is closed we probably can't accept GPL plugins in the addonpack. it is a different download than vvvv so it is hard to percieve it as one thing, so i might be wrong...
however to be totally sure it would be nice to either have a permission of the author of the bindings or to try to use other bindings...

sorry about the trouble

**Comment by mrft** [comment]
hello gregsn,

as I told you, I am still fighting with git a bit, that's probably why there are changed files that shouldn't have changed. Which files BTW?
And for the MyPlugins project, that's because it was explained that way on vvvv.org.
Another question about git: if you would have merged the pull request, would you have gotten my latest commit, or only the state it was in when I sent you the pull request? (just trying to understand git)

Anyway, so if I understand correctly, I should use someone else's bindings, or rewrite my own or get the athor to allow me to use his. I'll try to contact him about it. Maybe he's ok with it, as VLC was still GPL when he wrote his wrapper, but since it changed afterwards...

**Comment by mrft** [comment]
The author of LibVLC answered "Hi, You can use this entire library with the same license used by libVLC. Roman" (http://www.codeproject.com/Articles/109639/nVLC?msg=4342219#xx4342219xx), which means there should be no problem in using this as LGPL.

**Comment by gregsn** [comment]
this is great!!

uhm about pull requests: i am not really sure. let's just play with it (do a pull request and after that make a commit where you changed some white spaces at the end of a line... then we watch out if the commit is in or not). i never made a pull request. i am also still at getting into accepting pull requests ;) so: we are all leaning... just do another pull request and we'll see.

what is a bit irritating e.g. is that your pull request is full of commits (see above) that aren't from you. i am not so sure where those came from. they should already be in our sdk?! 
so let's just try again. make sure that you are up to date. 
 git pull upstream develop

if this again fails somehow and we run outof ideas what might be the problem on your side, i will try to accept the pull request with another technique, that allows me to make changes.

**Comment by gregsn** [comment]
well. i did the play with that and now you have MrFtPlugins.sln. let's see if that works for you and then we might introduce that as concept for all others as well.

**Comment by mrft** [comment]
The thing is that pull upstream completely messed up my repository (telling me it could not merge and had to delete files etc.). I hadn't done this since march when I first forked from the vvvv-sdk repo.

So what I did was, I checked out the upstream branch, and then I merged my branch with this one (instead of the other way around, which is what the pull request should do I guess). Something like that anyway.

MrFtPlugins sounds ok to me, I would have copied the MyPlugins.sln to another name if it were mentioned on the website. And I was thinking when opening the pull request: "what happens with the Myplugins? Because everyone will make his own changes to this file..."

I'll do my best to take a look at all this tonight or tomorrow.

**Comment by gregsn** [comment]
ok. i don't know exactly where the problems in your repo originated from. it really also may be that on our side we did something wrong. e.g. once we did a force push onto the repo to fix things. typically this is a no-go but we had a situation where we didn't find a way around that. 
so also still learning over here. but if your problems persist it might be better to checkout the sdk into another folder and try to work from there. after you are sure that you didn't loose anywork by that you could delete the original sdk folder? there might other ways...
sorry for the troubles

**Comment by azeno** [comment]
two issues arised on the build server:
1) when generating the nodelist (vvvv.exe /nodelist addonpack\lib\nodes), which creates each node, reads out its pins and destroys it, vvvv.exe stopped and waited for the user to click "OK" on a warning dialog saying VLC is not installed. could you remove that warning dialog and simply throw an exception? that way the node turns read for the user, and the generation of the nodelist would simply skip the node instead of waiting for someone to press ok (which is not nice on a build server).
2) so i installed latest VLC (version 2.0.3) on the build server to get it going again, but now the node list generation fails randomly with exception like this:
  Unbehandelte Ausnahme: System.AccessViolationException: Es wurde versucht, im geschützten Speicher zu lesen oder zu schreiben. Dies ist häufig ein Hinweis darauf, dass anderer Speicher beschädigt ist.
     bei LibVlcWrapper.LibVlcMethods.libvlc_media_player_stop(IntPtr libvlc_mediaplayer)
     bei VVVV.Nodes.Vlc.C0_5EX9_TextureVlcNode.MediaRenderer.Dispose()
     bei VVVV.Nodes.Vlc.C0_5EX9_TextureVlcNode.DisposeMediaRenderer(Int32 index)
     bei VVVV.Nodes.Vlc.C0_5EX9_TextureVlcNode.Dispose()
     bei VVVV.Nodes.Vlc.C0_5EX9_TextureVlcNode.Finalize()

we'll therefor have to set this plugin on ignore for now, until these issues are fixed.

**Comment by mrft** [comment]
1) I wanted to make it easy for the user to knwo what was going wrong, so I added the message teling him what to do. If I throw an exception, will it go to the tty renderer, whith the full message? In that case I could put the explanation in an exception.
2) I'll have to check whether it's possible that the libvlc_mediaplayer hasn't been created/intialized when MediaRenderer.Dispose() is called...

**Pull request merged**
