### PR TITLE
alternative Node for the Wiesemann & Theis WEB-IO

### PR DESCRIPTION
**Pull request by sebllll**
new Node for this Device: http://www.wut.de/e-5763w-13-inde-000.php

it receives the devices ouput-states, so you can avoid unneccesary retriggering (what can cause damage in some situations)

there are still 2 issues that should be solved before merging:
- when the node is deleted while it has a established connection, it's hard to reestablish the connection. 
  _(reproduce: delete node while connected > CTRL+Z)_
- COM object that has been separated from its underlying RCW cannot be used
  can happen if penetrating the Node with ALT+Rclick
  details: https://gist.github.com/sebllll/7353458

### CODE REVIEW

**Comment by sebllll** [comment]
these are the Devices Inputs. it has 12 Input-Pins and 12 Output-Pins. The Output-Pins can be set (and read), the Input-Pins can only be read.

**Comment by sebllll** [comment]
hmyes, we can change this. i refered to the manufacturers product name, which is Web-IO. And, i thought, we might get conflicts with 2 Nodes sharing the same name. i'm flexible here.

**Comment by joreg** [comment]
it seems you're missing the destructor but not sure if this is causing the problem since dispose should be called anyway. but it should be there anyway. and also compare: https://github.com/vvvv/vvvv-sdk/blob/develop/vvvv45/addonpack/src/nodes/plugins/Network/TCPClientAdvanced/TCPClientAdvanced.cs

**Comment by joreg** [comment]
doing so:
 IO (Devices Wiesemann+Theis Web-IO)
the nodenames differ in their version. and since the former was original for the Ditigal-EA device this seems to be its natural successor.

**Comment by joreg** [comment]
thinking about it the pinnaming on the other IOnodes is all confusing. The input pin on the node should be named "Output" as it is what goes out the device and the output pin on the node should be named "Input" as it is what goes into the device. and then that new pin should be named "Actual Output" as it reports (as i understand) what the actual state is on the devices output regardless of what has been set via the node, right?

**Comment by sebllll** [comment]
ok, i think i got it down to one scenario: resetting the node (ALT+RClick) when the connection is established.

what exactly is happening, when resetting a node? does it get disposed? does its deconstructor get called? or both?

i want to make sure, the tcpclient gets properly closed in this case.

**Comment by joreg** [comment]
Dispose() is called on removing a disposable plugin. so set a breakpoint there and check.

**Comment by sebllll** [comment]
should be in a stable state now. performs better (and more reliable) than the old node. Even two connections (two pcs, one wut) are possible with a little trick (as described in the helppatch).

added a "DoSend" Pin for convenience.

**Comment by joreg** [comment]
two more cosmeticas:
please start the help string with a capital A
and remove "IO, Devices" from tags, since those both are already showing in the nodes name

**Comment by joreg** [comment]
bump

**Comment by sebllll** [comment]
had still some issues with this stuff... reworked everything in here https://github.com/sebllll/vvvv-sdk/tree/web-io_reconnect 
I will make a new PR when the help-patch is updated... It works a bit different because some scenarios need a more spreadable way of sending Port-states to the Device.

So i suggest we keep this PR open, so it reminds me of finishing the new PR.

**Comment by joreg** [comment]
still keep that one open?

**Comment by joreg** [comment]
closing this because of inactivity

**Pull request closed without merging**
