### PR TITLE
init swizzle4d nodes

### PR DESCRIPTION
**Pull request by woeishi**
4d extension for swizzle nodes (join & split)

### CODE REVIEW

**Comment by tebjan** [comment]
the code looks pretty optimal. only one thing could be optimized... see my inline comment.
and help patches similar to the 3d ones would be a definite plus. :)
have you also wasted some thoughts about 2d <-> 4d swizzles?

**Comment by woeishi** [comment]
ah, yes. the help patches...

thought about the 2d-4d versions as well, but it seemed a little bit superfluous, since xy | zw is a zip 2d node, xz | yw is a vector 2d. so there would only be xw | yz left

**Comment by tebjan** [comment]
right, leave the 2d-4d stuff.. its fine as it is now.

**Comment by woeishi** [comment]
everything done, i guess

**Comment by tebjan** [comment]
ace!

**Comment by tebjan** [comment]
its in the addonpack, make a pull on vvvv-sdk i had to fix the location and the names of the help patches.

**Comment by woeishi** [comment]
aj, sorry, forgot to put them into lib instead of src

**Pull request merged**
