### PR TITLE
Some work on serialisation within vvvv

### PR DESCRIPTION
**Pull request by velcrome**
This pull request is twofolded
1. it has added DataContractAttributes to VMath structs and RGBAColor, so they serializes more efficiently with e.g. Json (no redundant data in the result)
2. it enhances the OSC routines in Utils.OSC to comply with extended OSC Specs 1.0 ( http://opensoundcontrol.org/spec-1_0 ), namely Blobs, Timestamps and Colors are now fully supported.

### CODE REVIEW

**Comment by velcrome** [comment]
The OSCTimeTag class was taken (and fixed) from https://bitbucket.org/pvarcholik/bespoke.osc

This is MS-PL, so some credit might be needed on the class

**Comment by tebjan** [comment]
Looks good, just one thing.. the array data of the matrices are named abcd or matrix. i think they should be called the same and starting with a capital letter, maybe Values or Matrix.

**Comment by joreg** [comment]
wait, may i suggest to get this split up into different pullrequests?
- one for vmath stuff
- one for osc stuff
- one for advanced map node

regarding "This is MS-PL, so some credit might be needed on the class" consider this your duty to find out and report accordingly, see: vvvv45\licenses

**Comment by velcrome** [comment]
I don't know how to "split this into different pullrequests". 
My individual commits explain what they are about though. Maybe that helps you as well.

As a free bonus, if you want to take the new plugins for a test drive, have a look at http://download.intolight.de/Map%20(Value%20Advanced)%20test.v4p 

This is not really a help patch, more a test patch that compares the behaviour of the old nodes vs. the new ones.

**Comment by velcrome** [comment]
FYI, the license stuff has been taken care of 5 days ago

**Comment by joreg** [comment]
it is easy to make individual PRs:
- do stuff that is not related to each other in individual branches
- push those branches to your fork
- make a PR from each of your branches against vvvv-sdk/develop

you can obviously still easily do this now:
- branch off a commit before your first change
- cherry-pick related commits to this branch
- push this branch
- make a PR from this branch against vvvv-sdk/develop

click, click, click...
let me be of help on irc if necessary. should make a very nice git-exercise

can you refer to the commit that takes care of the license-stuff? (didn't find anything)

**Comment by velcrome** [comment]
primarily, yes. 

i thought the extra vvvv precision is not needed over network. do you think that is okay?

**Comment by velcrome** [comment]
use PR 157, 158 and 159 instead

**Pull request closed without merging**
