### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by phlegma**
recoded the irrklang playback. now acts more than a sampleplayer than a filestream. 
updated to .net4
now loads libarys to play *.mp3 and *.flac files

### CODE REVIEW

**Comment by joreg** [comment]
hey phlegma, does this include changes that would need a legacy-version of the node not to break old patches?

also i am seeing some pin-naming-issues..will list those here later.

**Comment by joreg** [comment]
regarding pinnamings i'd suggest:

inputs:
File -> Filename (and make it the rightmost pin)
Seek Position -> Seek Time
Seek -> Do Seek
Playback Speed -> Speed
MainVolume -> Main Volume
PlayMode -> PlayMode
Enabel Effects -> Enable Effects

outputs:
Length -> Duration
Play Position -> Position

and in general please adapt the pin order to FileStream (DShow9) ie. play, loop, do seek, seek time, speed...and after those basics the more specific pins

and you have an extra Pause pin?! is there a difference to setting Play=0?

**Comment by phlegma** [comment]
ok pin renaming will be done. 
The Irrklang acts now more like a sample player. The sounds are triggered by bang. 
So that you can fire a sound as often you want e.g every frame. 
It is more usable. Think of click sounds or something similar. 
Pause can be used if the sound is looped. 

So there is the question if it should be a legacy because of changing the playback style.

**Comment by joreg** [comment]
still don't understand what separate Pause and Play pins are for.

and ja, sounds like a legacy node can make sense. so make sure to keep the original code there. unchanged, except setting the version to "Legacy". and modify the diffff.xml

**Comment by phlegma** [comment]
so 
did the legacy stuff 
did the renaming
did the diffff.xml stuff (please have a look)

want some more explanation on the Pause pin?

**Comment by joreg** [comment]
some more namings:
Stream Threashold -> Stream Threshold
Pos -> Position
View Diriection -> View Direction
Disable All Effekts -> Disable all Effects

in Irrklang.cs
in the PluginInfo please put a space after the comma betweeen sanch and phlegma

while at it...wouldn't the node better be named:
FileStream (Irrklang) or SamplePlayer (Irrklang)
since "Irrklang" is rather the category than the nodes name

and ja, please some info on the extra pause/stop pins

**Comment by phlegma** [comment]
Thank you for name spell checking. 
Totally confirm that the naming Filestream is better. -> Changed it.

Ok. Again play/  pause & stop. 
Because the play button is now a bang and not a toggle, and you can trigger more than one sound per slice, there should be the possibility to pause the whole sound layer of one slice and start it again. 
The stop button is there if you start more than one sound per slice you can stop the sounds step by step. 
Got that?

**Comment by phlegma** [comment]
like this?

**Comment by phlegma** [comment]
i thought the line above means the same. ok done.

**Comment by joreg** [comment]
right, it means the same. only the first line is for older patches...

**Comment by phlegma** [comment]
bump

**Comment by joreg** [comment]
oui. now in alpha, danks.

only realized now that the helppatch could need some tuning. seems to only produce constant noise here. some more explaining words of whats happening, what can be done with it would be fine: i suggest:
- left part of patch: simplest usecase: trigger sounds (without graphical output even)
- right part of patch: 2nd/more advanced usecase. (something like the one there is now)

also: opening an old patch correctly opens the now legacy node, but i get an exception.

**Pull request merged**
