### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mrft**
Changing the slice count seems stable now thanks to the devvvv's hints on Finalizing etc. Still, I am not sure if the GC does its job for all that's left. I mean, should I remove all of the IDispose stuff from all of the objects I create in the node, to make the GC do the cleaning up?

If it's not ok, I will have created a memory leak now (not that terrible, only when the slicecount goes down, but still). I am sure with the right hints I can get this cleaned up properly.

But maybe now it already passes the tests that were failing at this time.

Let me know.

### CODE REVIEW

**Comment by azeno** [comment]
i'd have done it the other way round. see the possibility to clean up for yourself as a good thing because it is up to you to decide when that should happen and in what order. as a rule of thumb, whenever you create something in a constructor which is disposable, implement a dispose method yourself and clean up the created object by a call to dispose.

**Comment by mrft** [comment]
What's the current status, is the build server fixed with these latest changes?

Are there still other problems that I should fix?

**Comment by azeno** [comment]
see if this command runs without errors
cmd /c vvvv.exe /nodelist addonpack\lib\nodes
if it succeeds there should be a nodelist.xml file in addonpack\lib\nodes. i recommend deleting it if you plan to write a new node in the future or you might wonder why your new node doesn't show up in the nodebrowser.
finally remove the ignore file from your plugin and commit / push it the usual way.

**Comment by mrft** [comment]
Seems to have worked so I committed the removal of the ignore file...

2012/10/20 Elias Holzer notifications@github.com

**Comment by azeno** [comment]
ok thanks. i'll merge it now.

**Pull request merged**
