### PR TITLE
$1 (DollarOne) 2d gesture recognizer

### PR DESCRIPTION
**Pull request by mhusinsky**
Here is a port of the $1 gesture recognizer by Jacob O. Wobbrock et al.
http://depts.washington.edu/aimgroup/proj/dollar/

It allows for simple and efficient 2d unistroke gesture recognition by simply defining gestures by example. It is simple to use and efficient in evaluation.

Comments welcome!
Please note that this commit contains also parts from pull request #249 which becomes obsolete with this one. (Sorry, I did not know how to do better).

### CODE REVIEW

**Comment by azeno** [comment]
Thank you very much - I'll do some re-formatings now and will change the project files a little so the cross-references are set up properly.

**Comment by azeno** [comment]
Oh and please add all those new nodes in the upcoming section here: http://vvvv.org/documentation/addons-change-log

**Comment by joreg** [comment]
sorry mhusinsky, your PR has been merged to quickly. please start a new PR fixing the things mentioned here. and don't forget the helppatches/modules then.

also: why "DollarOne" and not "OneDollar"? or even "OneDollarRecognizer"
compare: "OneEuroFilter"

**Comment by mhusinsky** [comment]
hej joreg,
sorry for the late reply.
thanks for the thorough inspectation. i was not aware of using versions to differentiate between categories - still learning a lot. one thing still not clear how to do right is multiple versions (e.g. Vector Spectral). just like that: 
Version = "Vector Spectral",...
?

regarding the naming of DollarOne vs. OneDollar. i was trying to be precise here - the original implementation always states "$1" (as contrary to "1€" with the filter). implementations by other guys are not consistent with the naming (both DollarOne and OneDollar exist). i don't have a preference - if you'd like it to be renamed that's fine with me and i'll include it in the next PR.

**Comment by joreg** [comment]
yes, multiple versions are separated by space. for full details also see:
http://vvvv.org/documentation/conventions.nodeandpinnaming

and yes, in order to make the two nodes show up next to each other i'd opt for "OneDollarRecognizer"

**Comment by mhusinsky** [comment]
okay.
one last question regarding the location of the modules and help:

now it is: addonpack\lib\nodes\modules\Gesture2dDollarOne\
better?: addonpack\lib\nodes\modules\OneDollarGesture
or even: addonpack\lib\nodes\modules\2d

?

**Comment by joreg** [comment]
addonpack\lib\nodes\modules\2d should do

**Pull request merged**
