### PR TITLE
ToString() functions for easier verbosing.

### PR DESCRIPTION
**Pull request by velcrome**

### CODE REVIEW

**Comment by velcrome** [comment]
in the meantime i did some pondering about the issue and i think, both ways are not perfect.

the use of this is to have a quick verbose of numerical contents within vectors. with both our ways very low and very high values will be hard to read. 

0.0000 could be anything betweeen -1/20.000 and +1/20.000

199893234.7877 is hard to read and usually you are only interested, that it's roughly 200 million

so I propose a system with generally only 3 digits and a postfix for the exponent by using letters like M (for million), k (for thousand), m (for a thousandth) etc.

examples would be 20M or 1.2 or 345k or 11.7m

**Comment by joreg** [comment]
hm..not sure if we should invent a new terminology here. in your arguing that with 199893234.7877 you'd only need to know that it is roughly 200M i'd argue that i am good to know that anything between -1/20.000 and +1/20.000 is roughly 0.0000

**Comment by velcrome** [comment]
I understand your reluctance, this is the default ToString() after all.

Yes, it would be some kind of new syntax in vvvv, but not in [real life](http://en.wikipedia.org/wiki/Metric_prefix).
And yes, there would still be rounding involved in providing short tty output, of course. This kind of rounding seems a good way for quick insight, because it removes some of its precision without sacrificing much accuracy, 
Readability of tiny and large numbers is clearly the focus of representing floating point this way. This is not for saving or parsing data, but for helping the user to get a quick look on the data in string format.

What's your understanding on this? Do you see a need to mimick IOBox (Value)?

**Comment by joreg** [comment]
yes, i'd mostly hesitate to introduce a new number format halfway. 
is there already a situation where we see those strings now? ie. any node that uses vector.tostring() somewhere?

**Comment by velcrome** [comment]
right now all vector structs inherit object.ToString() which provides only the class name, not any insight

**Comment by joreg** [comment]
ja, but is any node already calling tostring on vectors? if so for what?

**Comment by joreg** [comment]
closing this because of inactivity

**Pull request closed without merging**
