### PR TITLE
Virmata develop - I2C + String receive support

### PR DESCRIPTION
**Pull request by jnslxndr**
Last touches on help pachtes. Finally a PR...

### CODE REVIEW

**Comment by joreg** [comment]
hei jens, is this PR in any way depending on the the other with the binary ops? or is it "just" an independent update to the existing nodes?

**Comment by jnslxndr** [comment]
well, indirectly yes, but not directly relevant to #145. if someone uses the i2c, one might relatively soon want to shift some bits.

**Comment by jnslxndr** [comment]
but the node does not depend on #145 !

**Comment by jnslxndr** [comment]
that's why 2PRs :)

**Pull request merged**
