### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mrft**
Renamed VLC node to FileStream (VLC) version 1.0.

Added a simple helppatch.

Renamed and reordered some pins, to make it more similar to the original FileStream.

Licensing info should be ok now.

### CODE REVIEW

**Comment by gregsn** [comment]
thanks for the fixes!
our buildserver however still has problems:

Unbehandelte Ausnahme: System.AccessViolationException: Es wurde versucht, im geschützten Speicher zu lesen oder zu schreiben. Dies ist häufig ein Hinweis darauf, dass anderer Speicher beschädigt ist.
     bei LibVlcWrapper.LibVlcMethods.libvlc_media_player_stop(IntPtr libvlc_mediaplayer)
     bei VVVV.Nodes.Vlc.FileStreamVlcNode.MediaRenderer.Dispose()
     bei VVVV.Nodes.Vlc.FileStreamVlcNode.DisposeMediaRenderer(Int32 index)
     bei VVVV.Nodes.Vlc.FileStreamVlcNode.Dispose()
     bei VVVV.Nodes.Vlc.FileStreamVlcNode.Finalize()
C:\Users\buildserver\jenkins\jobs\vvvv45_alpha\workspace\public\vvvv45\addonpack\src\addonpack.csproj(89,5): error MSB3073: Der Befehl ""C:\Users\buildserver\jenkins\jobs\vvvv45_alpha\workspace\public\vvvv45\src..\vvvv.exe" /nodelist "....\temp\addonpack\lib\nodes"" wurde mit dem Code -1073741819 beendet.

**Comment by mrft** [comment]
Strange, I'll have to look at that....

How can I reproduce what your test-server is doing? Do you have more logs from earlier on?

**Comment by gregsn** [comment]
try this:
make MrFtPlugins your startup project,
in MrFtPlugins projects Debug tab:
Start external program: select vvvv.exe
Command line arguments: /nodelist "addonpack\lib\nodes"
Working directory: select the dir where vvvv.exe is.

now every node gets created and destroyed. all nodes' properties get collected and writen in a nodelist file.

you could also just try to create your plugin and destroy it by hand. just create a tester project that does that...

it might be necessary that you delete the ignore file

**Comment by azeno** [comment]
my guess is that the problem arises from the fact that you implement IDisposable and provide a finalizer, but you don't follow the pattern as described here: http://msdn.microsoft.com/en-us/library/fs2xkftw%28VS.100%29.aspx

i only had a quick look at it, but for example the DoubleMemoryBuffer frees the unmanaged memory in its dispose method, that's fine if the method only gets called once, but right now it'll probably get called twice (because of the finalizer) at some unknown point by the garbage collector and in the second call it will again free the unmanaged memory, which will cause undefined behaviour of the application.

you have two ways to solve this:
- remove the finalizer methods and make sure that the dipose method of your plugin calls dispose on all objects you created for this plugin.
- leave the finalizer and the dispose methods and implement them as described in the link above.

i always use option one when writing a plugin, as the plugin hosting code will call dispose on the plugin, no matter what. finalizers are only necessary if it is unknown for the library writer whether or not the client code calls dispose.

to investigate memory issues i recommend to use a memory profiler like this one: http://memprofiler.com/
start vvvv.exe with it, take a snapshot, create and remove your plugin and take a second snapshot, it will then tell you about objects which weren't disposed properly...

then about finding out whether or not vlc is installed. could you move the code were you try to lookup vlc to the plugin itself before accessing the types and methods which need it? as of now vvvv.exe seems to crash sometimes when instead the node should only turn red in case the constructor throws an exception.
also in the searchpath.txt file it would probably be better to set those search paths with the $(ProgramFiles)  or $(ProgramFilesx86) environment variable. you can expand those with a call to Environment.Expand("$(ProgramFiles)\VLC..."). as of now the search path is only correct for international windows installations.

**Comment by gregsn** [comment]
we had some bugs that forced us to put out beta28.1 ( patches got broken ). so sorrily vlc is not in the current addonpack. but as soon this integration works well and got some love from alpha testers we can always output a new addonpack... hope you are not offended...

**Comment by mrft** [comment]
@azeno: with some luck I will have a bit of time today to look at your comments (you might have pointed out the reason why changing the slicecount is still unstable)

@gregsn: not offended :)

**Pull request merged**
